### ISSUE TITLE
HTML fields don't init tiny mce until you add content

### ISSUE THREAD

**Issue by joe-hastings** [onespacemedia/cms#167]
For a html field inside a component using the compact inline view, if I add text to 'content' and hit save then the full editor appears.

![Screenshot 2019-07-04 at 16 59 50](https://user-images.githubusercontent.com/11661855/60678715-51ae7880-9e7d-11e9-8b06-9f05d10add56.png)

**Comment by AidanCurrah** [comment]
fixed in PT
