### ISSUE TITLE
Improve or remove `help_text` on PageBase

### ISSUE THREAD

**Issue by lewiscollard** [onespacemedia/cms#179]
Currently:

```
    slug = models.SlugField(
        help_text='A user friendly URL'
    )
```

Given that almost everything on a typical project inherits from this (including the CMS `Page` model itself) I think this could do with improvement; the slug is not a URL, and it is not clear to me how it is "user-friendly".

**Comment by Kane1994** [comment]
How about "A unique portion of the URL that is used to identify this specific Page using human-readable keywords (e.g., about-us)"

**Comment by lewiscollard** [comment]
Literally perfect, @Kane1994. Please go ahead.
