### ISSUE TITLE
Project template: 'gulp scripts' is behaving unexpectedly

### ISSUE THREAD

**Issue by lewiscollard** [onespacemedia/cms#55]
The `scripts` task in the project template is behaving incorrectly. When `gulp scripts` is run, the task never exits.

This breaks automated deployment, specifically, it stops us from adding `gulp scripts` to [`manage.py update`](https://github.com/onespacemedia/server-management/blob/master/server_management/management/commands/update.py), forcing us to run `manage.py update`, then ssh to the server and run `gulp scripts` interactively, kill it, then run `collectstatic`.

The correct behaviour would be for `gulp scripts` to work the same as `gulp styles`: exit after generating files.

**Comment by danielsamuels** [comment]
Given the changes to the front-end flow, is this issue now considered resolves?

**Comment by DanGamble89** [comment]
Yea, since we no longer use Gulp this is 'Resolved' in that sense.
