### ISSUE TITLE
Add the ability to host content on arbitrary URLs

### ISSUE THREAD

**Issue by danielsamuels** [onespacemedia/cms#89]
Many services such as Google Webmaster Tools require you to add specific content at a website endpoint to prove domain ownership. This typically requires updating the root URLconf and adding a template file to the project, followed by an app update. It would be much more useful if the CMS had a module, similar to the redirects module, which took an arbitrary URL and returned specified content (could just be text/plain content).

**Comment by jamesfoley** [comment]
Built app to handle static content https://github.com/onespacemedia/cms-static-content
