### ISSUE TITLE
Look into using Vagrant/Docker/Saltstack for local development + deployment

### ISSUE THREAD

**Issue by dan-gamble** [onespacemedia/cms#90]
Couple of helpful links for anyone looking into this:
### Docker
- https://docs.docker.com/compose/django/
- http://docs.docker.com/engine/installation/mac/
- http://michal.karzynski.pl/blog/2015/04/19/packaging-django-applications-as-docker-container-images/
- https://realpython.com/blog/python/django-development-with-docker-compose-and-machine/
### Vagrant
- https://github.com/aminehaddad/django-environment-in-vagrant
- https://github.com/FlipperPA/django-python3-vagrant

**Comment by danielsamuels** [comment]
Significant effort has been put into this under the [docker feature branch](https://github.com/onespacemedia/project-template/tree/feature/docker) on the onespacemedia/project-template repository. At this time, it appears that it's a non-trivial task to get the file watchers used in the front-end build tools to watch for changes.  There's a possibility that we could use Docker to deployments, but not for local development, but this is not an ideal scenario.

**Comment by danielsamuels** [comment]
https://puphpet.com/
